name: Streamlit App (Parallel)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install streamlit
      - name: Run Streamlit app
        run: |
          PORT=$(( 8500 + matrix.instance ))  # Hitung port di luar perintah streamlit
          streamlit run app.py --server.port $PORT  
        env:
          STREAMLIT_SERVER_PORT: $(( 8500 + matrix.instance ))
