name: Streamlit App (Parallel)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4]
    env:  
      PORT: ${{ 8500 + matrix.instance }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install streamlit
      - name: Run Streamlit app
        run: |
          echo ${{ env.PORT }} # Menampilkan nilai PORT untuk debugging
          streamlit run app.py --server.port ${{ env.PORT }}  
